import Head from 'next/head';
import Image from 'next/image';
import classNames from 'classnames/bind';

import styles from '@/styles/Home.module.scss';
import Link from 'next/link';

export default function Home() {
	const cx = classNames.bind(styles);
	return (
		<>
			<Head>
				<title>Star Wars App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={cx('home')}>
				<div className={cx('home__cta')}>
					<h1 className={cx('home__title')}>
						<strong className={cx('home__title_strong')}>
							Find
						</strong>{' '}
						all your{'\n'}favorite{'\n'}
						<strong className={cx('home__title_strong')}>
							character
						</strong>
					</h1>
					<p className={cx('home__text')}>
						You can find out all the{'\n'}information about your
						favorite{'\n'}characters
					</p>
					<Link href={'/characters'} className={cx('home__btn')}>
						See more...
					</Link>
				</div>
				<Image
					src={'/banner_img.png'}
					alt={'Yoda'}
					className={cx('home__banner-img')}
					width={793}
					height={680}
				/>
			</div>
		</>
	);
}
